# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# export colors only if interactive
if [[ "${-}" = *i* ]]; then
  export RED="$( tput setaf 1 )"
  export GREEN="$( tput setaf 2 )"
  export YELLOW="$( tput setaf 3 )"
  export CYAN="$( tput setaf 6 )"
  export NC="$( tput sgr0 )"
fi

alias ls='ls --color=auto'
alias ll='ls -l'

export EDITOR=vim

# don't put duplicate lines in the history. See bash(1) for more options
export HISTFILESIZE=300000    # save 300000 commands
export HISTCONTROL=ignoredups    # no duplicate lines in the history.
export HISTSIZE=100000
export HISTIGNORE="&:[bf]g:exit"
export HISTTIMEFORMAT='+%Y-%m-%d %H:%M:%S'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s histappend
# save all lines of a multiple-line command in the same history entry
shopt -s cmdhist
# correct some misspelling
shopt -s cdspell

# reread history file all the time
export PROMPT_COMMAND='history -a'

#aliases
alias histupd="history -n"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
which rlwrap >/dev/null 2>&1 && {
  alias sqlplus='rlwrap sqlplus'
  alias rman='rlwrap rman'
  alias asmcmd='rlwrap asmcmd'
  alias adrci='rlwrap adrci'
  alias dgmgrl='rlwrap dgmgrl'
}

export PS1='[${ORACLE_SID:-"X"}:$( basename ${ORACLE_HOME:-"X"})]${YELLOW}\u@\h:\w$ ${NC}'
if [[ ${USER} = grid ]]; then
  export PS1='[${ORACLE_SID:-"X"}:$( basename ${ORACLE_HOME:-"X"})]${CYAN}\u@\h:\w$ ${NC}'
elif [[ ${USER} = root ]]; then
  export PS1='[${ORACLE_SID:-"X"}:$( basename ${ORACLE_HOME:-"X"})]${RED}\u@\h:\w# ${NC}'
fi
