# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

alias ls='ls --color=auto'
alias ll='ls -l'

export EDITOR=vim

# don't put duplicate lines in the history. See bash(1) for more options
export HISTFILESIZE=300000    # save 300000 commands
export HISTCONTROL=ignoredups    # no duplicate lines in the history.
export HISTSIZE=100000
export HISTIGNORE="&:[bf]g:exit"
export HISTTIMEFORMAT='+%Y-%m-%d %H:%M:%S'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s histappend
# save all lines of a multiple-line command in the same history entry
shopt -s cmdhist
# correct some misspelling
shopt -s cdspell

# reread history file all the time
export PROMPT_COMMAND='history -a'

#aliases
alias histupd="history -n"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias sqlplus='rlwrap sqlplus'
alias rman='rlwrap rman'
alias asmcmd='rlwrap asmcmd'
alias adrci='rlwrap adrci'
alias dgmgrl='rlwrap dgmgrl'

#export PS1='[$ORACLE_SID:$( basename $ORACLE_HOME )][\u@\h \W]$ '

export PS1='[${ORACLE_SID:-"X"}:$( basename ${ORACLE_HOME:-"X"})]\[\033[1;33m\]\u@\h\[\033[1;34m\]:\[\033[1;33m\]\w\[\033[0m\]\[\033[1;33m\]\$\[\033[0m\] '
