#!/bin/bash

iface=${1:-"eth0"}
action=${2:-"up"}

echo "iface = ${iface}"
echo "action = ${action}"

[[ "${action}" != "up" ]] && exit 0

host="$( hostname -s )"
domain="$( hostname -d )"
domain=${domain:-"vm.local"}

dns=192.168.1.2

ipaddr=$( ip -4 -o addr show dev ${iface} | awk '{ print $4 }' | cut -d '/' -f1 )

# depending on which number the interface has in the list we assign
# 2: -p
# 3: -i
# everything else remains the same
iface_no=$( ip -o -4 link show | grep ether | cut -d ':' -f2 | tr -d ' ' | awk "/${iface}/ { print NR; }" )

case $iface_no in
  1) host=${host} ;;
  2) host="${host}-p" ;;
  3) host="${host}-i" ;;
  *|?) exit 0 ;;
esac

dnsip="$( dig @${dns} +nocmd +noall +answer A ${host}.${domain} | awk '{ print $NF }' )"
echo "${iface} IP = ${ipaddr}"
echo "DNSIP for ${host}.${domain} = ${dnsip}"

if [[ "${ipaddr}" != "${dnsip}" ]]; then
echo "
server ${dns}
zone ${domain}
update delete ${host}.${domain} A
update add ${host}.${domain} 86400 A ${ipaddr}
show
send" | nsupdate
fi
